universe            = vanilla
executable          = /afs/cern.ch/user/e/escheull/nobackup/modularized_nurd_hlt_con_ae/condor_convert_zerobias.sh

output              = /afs/cern.ch/user/e/escheull/nobackup/modularized_nurd_hlt_con_ae/condor_logs/convert_zerobias.out
error               = /afs/cern.ch/user/e/escheull/nobackup/modularized_nurd_hlt_con_ae/condor_logs/convert_zerobias.err
log                 = /afs/cern.ch/user/e/escheull/nobackup/modularized_nurd_hlt_con_ae/condor_logs/convert_zerobias.log

request_CPUs        = 4
request_memory      = 48GB
+JobFlavour         = "workday"

queue
