apiVersion: v1
kind: Pod
metadata:
  name: contrastive-setup
  namespace: axol1tl
spec:
  restartPolicy: Never
  containers:
    - name: setup
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
      command: ["sleep", "3600"]
      volumeMounts:
        - name: axovol
          mountPath: /axovol
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
        limits:
          memory: "16Gi"
          cpu: "4"
  volumes:
    - name: axovol
      persistentVolumeClaim:
        claimName: axovol
